### ISSUE TITLE
Automated Build from Pushed Local Folder

### ISSUE THREAD

**Issue by psychemedia** [amalfra/docker-hub#10]
I'm not sure if this is possible from the Docker hub side, but it would be really handy if there was a way to support a *Zeit Now* style mechanic whereby I could push a build directory to Docker hub and then let Docker hub build the container remotely for me - essentially, an *automated build from an uploaded archive* model.

Docker Hub is capable of pulling content from a Github repo as part of an automated build - the question is, can the automated build be co-opted so we can push repo contents ourselves to the automated build endpoint on Docker hub?

**Comment by amalfra** [comment]
@psychemedia don't think what you meant is related to this cli tool. docker hub cli tool is basically for viewing details about images in docker hub. it's like an alternative for viewing docker hub hosted images in console instead of opening hub.docker.com

**Comment by amalfra** [comment]
closing as this is not related. Feel free to reopen if not.
