### ISSUE TITLE
--all to "repos" would be nice

### ISSUE THREAD

**Issue by hrw** [amalfra/docker-hub#5]
We have 317 images on Docker hub. Would be nice to be able to get whole list instead of paging 22 times.

**Comment by amalfra** [comment]
@hrw I will look into this next week. As you may know, the API won't return all data in one request. So making multiple requests and waiting for them to complete before painting table will create delay for big lists. We can maybe keep showing results continuously, but I will have to look into how that can be done.

**Comment by hrw** [comment]
Check my hrw/docker-utils repo for code. I also have there a part to remove tag from an image.

**Comment by amalfra** [comment]
@hrw Thank you, I will have a look.

**Comment by tomviner** [comment]
Here's an example patch to get all pages of tags: https://github.com/amalfra/docker-hub/compare/master...tomviner:feature-all_pages

**Comment by amalfra** [comment]
@tomviner awesome! If it's okay please feel free to open a pr. Let me know if you plan to or I can try to do this.

**Comment by amalfra** [comment]
@hrw latest release https://github.com/amalfra/docker-hub/releases/tag/2.1.0 adds this feature.
Now you can use `--all-pages` like `docker-hub tags --orgname docker --reponame ucp --all-pages` .

Special thanks to @tomviner !
