### ISSUE TITLE
Running docker-hub without any prompts

### ISSUE THREAD

**Issue by pascalandy** [amalfra/docker-hub#7]
Continuing from https://github.com/amalfra/docker-hub/issues/6#issuecomment-390409064

I would love to launch this container without any prompts. 

I feel it would be valuable to have a config file where we could configure:

```
DOCKERHUB_USER=myuser1234
DOCKERHUB_PASS=h5h356h356hy
```

This way we could build a Dockerfile and run the image without interactions.

The VARS could also be passed along when running the container and override the default VARS:
Per example:

```
IMG_NAME="myuser:dockerhub-cli:1.0" \
\
echo && echo && docker run --rm -it \
-e DOCKERHUB_USER=myuser1234 \
-e DOCKERHUB_PASS=h5h356h356hy \
"$IMG_NAME" \
\
sh -c 'docker-hub users --username docker';
```

Hope it make sense :)

**Comment by amalfra** [comment]
@pascalandy I don't think storing docker hub password in config is good idea. What is required for requesting api is the token that is received after logging in. I can add a docker-hub login command that will use username and password from user and get token from docker hub and save it to docker-hub's config file. 
and can add support for envs that will be used just for the command to execute ie; it will generate tokens using the credentials but won't be persisted anywhere

**Comment by pascalandy** [comment]
This is exactly what I had in mind :) 
That would be awesome :)

**Comment by amalfra** [comment]
A quick update: checkout the latest version, docker-hub login command support has been added. env support on the way!

**Comment by amalfra** [comment]
@pascalandy The env feature is live! Please checkout v1.8 to try it. The envs are:

  * DOCKER_HUB_USERNAME - Your Docker Hub username
  * DOCKER_HUB_PASSWORD - Your Docker Hub password

**Comment by pascalandy** [comment]
I'm a bit confused to test this as there is no Dockerfile or no docker image to test.

I guess the Dockerfile would look like this:

```
FROM: python:3.6.5-alpine3.7

RUN set -ex && \
  pip3 install docker-hub;
```

From that image, I would do

```
IMG_NAME="myuser:dockerhub-cli:1.8" \
\
echo && echo && docker run --rm -it \
-e DOCKERHUB_USER=myuser1234 \
-e DOCKERHUB_PASS=h5h356h356hy \
"$IMG_NAME" \
\
sh -c 'docker-hub repos --username docker';
```

**Comment by amalfra** [comment]
yes, just make sure envs are DOCKER_HUB_USERNAME and DOCKER_HUB_PASSWORD as mentioned in readme

**Comment by pascalandy** [comment]
Good news!

I built the image and ran:

```
IMG_NAME="devmtl/dockerhub-cli:1.8"

docker run --rm -it \
-e DOCKERHUB_USER=myuser \
-e DOCKERHUB_PASS=mypassword! \
"$IMG_NAME" sh -c 'docker-hub tags --orgname devmtl --reponame ghostfire'
```

#### The system returns:

```
Status: Downloaded newer image for devmtl/dockerhub-cli:1.8
#####################################
 Found 376 results. On page 1 of 26
#####################################
+---------------------+-----------+------------------+
| Name                | Size      | Last updated     |
+=====================+===========+==================+
| edge                | 174.68 MB | 2018-06-04 16:25 |
+---------------------+-----------+------------------+
| 1.23.1-edge-1663cc4 | 174.68 MB | 2018-06-04 16:25 |
+---------------------+-----------+------------------+
| 1.22.8              | 127.49 MB | 2018-06-04 02:23 |
+---------------------+-----------+------------------+
| 20180604_02H21_38   | 127.49 MB | 2018-06-04 02:23 |
+---------------------+-----------+------------------+
| 1.22.8-5d81064      | 127.49 MB | 2018-06-04 02:23 |
+---------------------+-----------+------------------+
(and more ...)

Tip: You are not authenticated with Docker Hub. Hence only public resoruces will be fetched. Try authenticating using `docker login` or `docker-hub login` command to see more.
```

1) You see the warning at the end? This should not be there.
2) There is also a typo in the word 'resoruces'

**Comment by amalfra** [comment]
envs are wrong. Use DOCKER_HUB_USERNAME  and DOCKER_HUB_PASSWORD  instead of DOCKERHUB_USER and DOCKERHUB_PASS

**Comment by pascalandy** [comment]
That looked bad :-p
Thank you!
